version: '3.7'

services:

  sample-prod:
    container_name: react_koboard
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - REACT_APP_KOBOARD_API_URI = http://koboard_api:5000
    networks:
      - rvp_default

networks:
  rvp_default:
    external:
      name: rvp_default